/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    Auth: {
        region: "us-east-1", // Ensure this is correct
        userPoolId: "us-east-1_e0nDw8WUP",
        userPoolWebClientId: "2v0bq5pkeuurjidiu82i08cd64"
    }
};


export default awsmobile;
